spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: 123
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  apache:
    rocketmq:
      consumer:
        PushConsumer:
          PushConsumer
      producer:
        producerGroup:
          Producer
      namesrvAddr:
        192.168.15.222

  redis:
    host: 192.168.15.111
    port: 7389
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms
    password: b840b7be6c52
  cache:
    type: redis
    cacheExpires:
                100
    ehcache:
      config: classpath:ehcache.xml

  logging:
    level:
      debug

server:
  port: 8081
mybatis:
  type-aliases-package: com.sys.tryxx.domain
  mapper-locations: classpath:mapper/*.xml
  show-sql: true

#下面为连接池补充设置   
initialSize: 5   
# 配置获取连接等待超时的时间      
maxWait: 60000   
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒   
timeBetweenEvictionRunsMillis: 60000   
# 配置一个连接在池中最小生存的时间，单位是毫秒    
minEvictableIdleTimeMillis: 300000   
validationQuery: SELECT 1 FROM DUAL   
testWhileIdle: true   
testOnBorrow: false   
testOnReturn: false   
# 打开PSCache，并且指定每个连接上PSCache的大小   
poolPreparedStatements: true   
connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000   
# 合并多个DruidDataSource的监控数据    
useGlobalDataSourceStat: true


management:
  server:
    port: 54000
    health:
      mail:
        enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    app:
      name:tryxx
